### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by hk1ll3r**
I took today to make the changes we discussed to the repository.

1) Removed main project's dependency on JSON library.
Also simplify JSON format used in the main project and add classes to plug-in data providers. It is useful in cases where the Data comes from outside, like from json, csv, etc. The IDataProviderInterface let's the lib users provide data from whatever source.

2) Created DataConversion project to convert input json into 1) processed json and 2) .cs file.
The current settings generate the 2 output files per input file in resources/ folder. The .cs files then have to be moved to the main project. The class name needs to be manually renamed.

3) Added test cases for major US cities and world capitals. Both failing but provide a baseline to improve the test data and geo data on.

I don't have more time to spend on the pull request. If you need minor changes, please accept the pull request and make them after. I also hadn't pulled your recent changes from 3 days ago. The currency changes are fine but I've used NewtonsoftJson in the converter project. So might be easier to rebase on this.

Cheers!

### CODE REVIEW

**Comment by InquisitorJax** [comment]
Thanks for this... I pushed a PR to fix the merge conflicts.
If you could pull that into your branch to resolve the merge conflicts (if that's possible?), then I can merge this PR, and take it from there.

**Comment by hk1ll3r** [comment]
hmm not sure what you are trying to do here. I accepted your pull request into my master branch. Do you need anything else?

**Comment by InquisitorJax** [comment]
mmm, I see the merge conflicts aren't resolved - that PR probably should have been to your 'pullrequest' branch :(
Could you merge from your master to pullrequest, and then push those changes up, so the merge conflicts can be resolved here?
Then I can merge in this PR.

**Comment by hk1ll3r** [comment]
done

**Pull request merged**
