### PR TITLE
Remove dependency on JSON.net, target netstandard2.0

### PR DESCRIPTION
**Pull request by hk1ll3r**
I was getting JSON parse errors on mobile phones when using the library. Everything ran fine on my laptop. Turns out JSON.net library was the culprit. JSON.net is very common yet isn't supported on some platforms  (in Unity for example, xamarin on phones doesn't support JIT).

Here are the changes I made to get rid of the JSON lib. Apart from using ValueTuple unnecessarily, the change is a positive change. Tests pass.

- Removed JSON strings from code. Replaced them with calls to class constructors. Adds compile time type safety and prevents JSON parse errors when modifying the data.
- Removed dependency on JSON.net lib. 
- Simplified data structures (AreaData.cs)

Downside: 
I unnecessarily used value tuples in the code which prevented me from keeping the target as .netstandard1.0. Works with .netstandard2.0. You could replace value tuples with a custom struct like Point, for me now worth the trouble at this step.

### CODE REVIEW

**Comment by InquisitorJax** [comment]
wow - this looks like it was a lot of effort.
Unfortunately I don't think I'll pull this in, as it diverts from the standard json format that is used by the people that maintain the data - so this will make it more effort to make updates to the data should there be differences in accuracy.

Interesting that you mention it doesn't work on xamarin apps - there is a sample xamarin project in the code where it seems to be working fine?

regardless - I've just submitted an update that:
- replaces Json.NET with System.Text.Json
- added support for currency symbols (which is now possible with the update to .NET Standard 2.0)

not sure if this makes a difference for you? Let me know ;)

**Comment by hk1ll3r** [comment]
I'm not sure whether replacing json.net with System.Text.Json helps with my case. The latter library is not part of netstandard, so to use it my environment (Unity) I'd need to include a microsoft dll, which might have the same issue.

I saw the xamarin project but didn't run it. I think even that could face issues on android and ios. This page mentions the problem with reflection on those platforms and specifically mentions json.net: https://docs.microsoft.com/en-us/xamarin/tools/live-player/troubleshooting

Apart from the json library issue, there are two points to my changes:
From the perspective of **code cleanliness**, embedding json inside a source code file and parsing that static data at runtime is *bad*. Modifying the data is hard because of formatting and you can't catch formatting errors easily. For example if someone modifies the json in the .cs file and forgets a bracket, it will cause a runtime json parse error. With static data it is better to validate things at compile time.
You have a point about the source data and the burden of converting it to c# code. In my opinion it would be better to keep the json around in a text file alongside the code files. That way the json file can be json-validated. IDE's have them, notepad++ has plugins for it, etc. 

From **performance** standpoint, you parse json on the fly for each query, so if an application performs a lot of geocode lookups, you parse all the json for the areas that fail many times, even though that data is static. So one optimization would be to parse json once at load into an array. Then at query time, use the parsed array. The static constructor is a good place for that.

These said, It's fine if you don't want to take this pull request in. It is your repository after all. The library is lightweight enough for users to make changes :)

**Comment by InquisitorJax** [comment]
You make some very good points, particularly around runtime performance - I'll keep that in mind for the next update - thanks :)

**Comment by InquisitorJax** [comment]
I think if we had a code_gen project with the reference json data, and could code generate (overwrite) the static AreaData files, that would be the best of both worlds: performance + maintainability.

**Comment by hk1ll3r** [comment]
I agree.
I can help with that. Let me know.

In the gen project we could simplify the json too (similar to below as is in my fork), record all coordinates as multipolygon. 

```
    public struct AreaData 
    {
        public string id;
        public string name;
        public string fips;
        public MultiPolygon geometry;

        public AreaData(string id, string name, string fips, MultiPolygon geometry) 
        {
            this.id = id;
            this.name = name;
            this.fips = fips;
            this.geometry = geometry;
        }
    }

    public struct MultiPolygon {
        public (double, double)[][] coordinates;

        public MultiPolygon((double, double)[][] coordinates) 
        {
            this.coordinates = coordinates;
        }
    }
```

**Comment by InquisitorJax** [comment]
My main concern would be how easy it would be to paste in the external json coordinate data, and just run the code gen to regenerate the AreaData instances in the main project.
If you could get something like that implemented, I'd be more than happy to merge the PR - unfortunately my time is super limited atm between day job and trying to release my own product, so I'm not sure this will be a priority for me in the near future.
If you do have capacity to go ahead with the suggestion, let me know if I can do anything the assist - your input is greatly appreciated.

**Comment by hk1ll3r** [comment]
I'm pretty busy this week, but can spare some time this weekend to get a gen project up and running. Will open another pull request once its done. 
Which files do you use as source? The 3 json files under resources folder? (gz_2010_us_040_00_500k.json, etc.)?
What is the role of resources/state.xml? 
Where is the source of the data for countries data?

**Comment by InquisitorJax** [comment]
... was thinking you could just move the existing country data from the project into the gen project?
There are some links to external country geojson data in the CountryData.cs file, but I wouldn't worry about that for now.

The 3 json files are just different levels of accuracy - you should be good with the *20m.json version.
The states.xml was just another reference file for polygon data - but in xml format - which is not as common as json, so I think you can ignore that.

**Comment by hk1ll3r** [comment]
you mean convert CountryData.cs to .json first, to use it as the source for country data json in the code-gen project?

**Comment by InquisitorJax** [comment]
Perhaps even just consider moving the existing CountryData.cs & UsaStateData.cs as-is into the code-gen project, and then iterate over the DATA list, deserializing the json to code gen the main project AreaData instances as you have them with the static initializers.
what do you think?

**Pull request closed without merging**
